SocialCode/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
    # Auth
    path("register/", user_view.register, name="register"),
    path(
        "login/",
        auth_view.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_view.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    # Profilw
    path("profile/", user_view.profile, name="Profile"),
    path("<str:username>/", user_view.profile, name="view_profile"),
    path("profile/update", user_view.profile_update, name="profile_update"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.home, name="home"),
    #    crud
    path("questions/", views.QuestionListView.as_view(), name="question_list"),
    path("questions/new/", views.QuestionCreateView.as_view(), name="question_create"),
    path(
        "questions/<slug:slug>/",
        views.QuestionDetailView.as_view(),
        name="question_detail",
    ),
    path(
        "questions/<slug:slug>/update/",
        views.QuestionUpdateView.as_view(),
        name="question_update",
    ),
    path(
        "questions/<slug:slug>/delete/",
        views.QuestionDeleteView.as_view(),
        name="question_delete",
    ),
    path("questions/<slug:slug>/upvote/", views.upvote_question, name="upvote_question"),
    path("questions/<slug:slug>/downvote/", views.downvote_question, name="downvote_question"),

]

base/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from django.utils.text import slugify
from ckeditor.fields import RichTextField
# Create your models here.


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=1000)
    content = RichTextField(null=True, blank=True)
    
    date_created = models.DateTimeField(default=timezone.now)
    # tags = models.ManyToManyField(Tags, blank=True)
    # detail = RichTextField(blank=True, null=True)
    views_count = models.IntegerField(default=0)
    upvotes = models.ManyToManyField(User, related_name="question_upvotes", blank=True)
    downvotes = models.ManyToManyField(User, related_name="question_downvotes", blank=True)

    slug = AutoSlugField(unique=True, populate_from="title")
    def comment_count(self):
        return self.comment.count()
    def __str__(self):
        return f"{self.title} - {self.user.username} - Question"

    def get_absolute_url(self):
        return reverse("base:question_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.id:  # Check if the object has not been saved (i.e., it's a new question)
            slug = kwargs.get("slug")
            if slug:
                try:
                    question = Question.objects.get(slug=slug)
                    self.question = question
                except Question.DoesNotExist:
                    pass  # Regenerate slug if a question with the same slug doesn't exist

        super().save(*args, **kwargs)



class Comment(models.Model):
    question = models.ForeignKey(Question, related_name="comment", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  # Use User model for the commenter
    content = models.TextField(null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    
    
    def __str__(self):
        comment_number = self.question.comment.filter(date_created__lt=self.date_created).count() + 1
        return f"comment[{comment_number}] --- {self.question.title} -- {self.user.username}"
    
    def get_absolute_url(self):
        return reverse("base:question_detail", kwargs={"slug": self.question.slug})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

base/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # Correct the typo: 'mdoel' to 'model'
        fields = ['content']  # Remove 'name' field if it's not part of your Comment model
        
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'}),  # Correct the field name: 'body' to 'content'
        }

base/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Question, Comment
from users.models import Profile
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .forms import CommentForm
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
# Create your views here.
def home(request):
    return render(request, "home.html")


# crud function

from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import Question
from users.models import Profile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def home(request):
    return render(request, "home.html")


# crud function
class QuestionListView(ListView):
    model = Question

    context_object_name = "questions"
    ordering = ["-date_created"]
    paginate_by = 2  # Number of questions per page

    def get_queryset(self):
        # Get the queryset for the questions
        questions = super().get_queryset()
        # Prefetch the related Profile objects to avoid N+1 queries
        questions = questions.select_related("user__profile")
        return questions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Paginate the questions queryset
        questions = self.get_queryset()
        paginator = Paginator(questions, self.paginate_by)
        page = self.request.GET.get("page")
        try:
            questions = paginator.page(page)
        except PageNotAnInteger:
            questions = paginator.page(1)
        except EmptyPage:
            questions = paginator.page(paginator.num_pages)
        context["questions"] = questions
        return context


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'base/question_detail.html'  # Use your question detail template

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = self.object  # Get the question object from the view
        comments = Comment.objects.filter(question=question).select_related('user__profile')
        comment_form = CommentForm()  # Create a new instance of the comment form
        # context['comments'] = comments
        # context['comment_form'] = comment_form
        
        upvotes = question.upvotes.count()
        downvotes = question.downvotes.count()
        difference = upvotes - downvotes

        context['comments'] = comments
        context['comment_form'] = comment_form
        context['upvotes'] = upvotes
        context['downvotes'] = downvotes
        context['difference'] = difference
        return context

    def post(self, request, *args, **kwargs):
        question = self.get_object()  # Get the question object
        comment_form = CommentForm(request.POST)  # Bind the form data to the CommentForm

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = self.request.user
            comment.question = question
            comment.save()
        

            # Redirect to the same page after a successful comment submission
            return HttpResponseRedirect(self.request.path_info)

        # If the form is not valid, re-render the question detail page with errors
        context = self.get_context_data(**kwargs)
        context['comment_form'] = comment_form
        return self.render_to_response(context)

class QuestionCreateView(CreateView):
    model = Question
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class QuestionUpdateView(UserPassesTestMixin, UpdateView):
    model = Question
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.user:
            return True
        else:
            return False


class QuestionDeleteView(UserPassesTestMixin, DeleteView):
    model = Question
    success_url = "/"

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.user:
            return True
        else:
            return False

# class CommentDetailView(CreateView):
class CommentDetailView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'base/comment_form.html'  # Use your custom HTML template


    def form_valid(self, form):
        question = get_object_or_404(Question, slug=self.kwargs['slug'])
        form.instance.question = question
        form.instance.user = self.request.user
        form.save()
        return redirect('base:question_detail', slug=self.kwargs['slug'])


def upvote_question(request, slug):
    question = get_object_or_404(Question, slug=slug)
    if request.user in question.downvotes.all():
        question.downvotes.remove(request.user)
    if request.user not in question.upvotes.all():
        question.upvotes.add(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

def downvote_question(request, slug):
    question = get_object_or_404(Question, slug=slug)
    if request.user in question.upvotes.all():
        question.upvotes.remove(request.user)
    if request.user not in question.downvotes.all():
        question.downvotes.add(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

base/templates/base/question_confirm_delete.html
{% extends "base.html" %} {% block content %} {% load humanize %}
	
<header id="header" class="fixed-header
" style="
position: fixed;
top: 50px;
width: 100%;
background-color: #2f3239; /* Set the background color as needed */
z-index: 1000; /* Ensure the header is above other elements */
 /* Add smooth transition effect */
">



<section class="container clearfix">
  <div class="logo"><a href="{% url "base:home"%}"><img alt="" src="/static/images/logo2.png"></a></div>
  <nav class="navigation">
    <ul>
      <li><a href="{% url "base:home"%}">Home</a>
        <ul>
          <li><a href="index.html">Home</a></li>
          <li><a href="index_2.html">Home 2</a></li>
          <li><a href="index_boxed_1.html">Home Boxed 1</a></li>
          <li><a href="index_boxed_2.html">Home Boxed 2</a></li>
          <li><a href="index_no_box.html">Home No Box</a></li>
        </ul>
      </li>
      {% if user.is_authenticated %}

        <li class="ask_question "><a href="{% url 'base:question_create' %}">Ask Question</a></li>
      {% else %}
        <li class="ask_question"><a href="{% url 'login' %}">Ask Question</a></li>
      
      {% endif %}
      
      <li class="current_page_item"><a href="cat_question.html">Questions</a>
        <ul>
          <li><a href="cat_question.html">Questions Category</a></li>
          <li><a href="single_question.html">Question Single</a></li>
          
        </ul>
      </li>
      <li><a href="user_profile.html">User</a>
        <ul>
          <li><a href="user_profile.html">User Profile</a></li>
          <li><a href="user_questions.html">User Questions</a></li>
          <li><a href="user_answers.html">User Answers</a></li>
          <li><a href="user_favorite_questions.html">User Favorite Questions</a></li>
          <li><a href="user_points.html">User Points</a></li>
          <li><a href="edit_profile.html">Edit Profile</a></li>
        </ul>
      </li>
      <li><a href="blog_1.html">Blog</a>
        <ul>
          <li><a href="blog_1.html">Blog 1</a>
            <ul>
              <li><a href="blog_1.html">Right sidebar</a></li>
              <li><a href="blog_1_l_sidebar.html">Left sidebar</a></li>
              <li><a href="blog_1_full_width.html">Full Width</a></li>
            </ul>
          </li>
          <li><a href="blog_2.html">Blog 2</a>
            <ul>
              <li><a href="blog_2.html">Right sidebar</a></li>
              <li><a href="blog_2_l_sidebar.html">Left sidebar</a></li>
              <li><a href="blog_2_full_width.html">Full Width</a></li>
            </ul>
          </li>
          <li><a href="single_post.html">Post Single</a>
            <ul>
              <li><a href="single_post.html">Right sidebar</a></li>
              <li><a href="single_post_l_sidebar.html">Left sidebar</a></li>
              <li><a href="single_post_full_width.html">Full Width</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <li><a href="right_sidebar.html">Pages</a>
        <ul>
          <li><a href="login.html">Login</a></li>
          <li><a href="contact_us.html">Contact Us</a></li>
          <li><a href="ask_question.html">Ask Question</a></li>
          <li><a href="right_sidebar.html">Right Sidebar</a></li>
          <li><a href="left_sidebar.html">Left Sidebar</a></li>
          <li><a href="full_width.html">Full Width</a></li>
          <li><a href="404.html">404</a></li>
        </ul> 
      </li>
      <li><a href="shortcodes.html">Shortcodes</a></li>
      <li><a href="contact_us.html">Contact Us</a></li>
      {% comment %} <li><a href="contact_us.html"><img style="    width: 40px; height: 40px;" src="{% static 'images/patterns/bg13.png' %}"></img></a></li> {% endcomment %}
      
      {% if user.is_authenticated %}
      
        <li><a href="{% url "logout" %}">Logout</a></li>
      {% endif %}
    </ul>
  </nav>
</section><!-- End container -->
</header>


<div class="breadcrumbs" style="padding-top: 86px">
  <section class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>This is my first Question</h1>
      </div>
      <div class="col-md-12">
        <div class="crumbs">
          <a href="#">Home</a>
          <span class="crumbs-span">/</span>
          <a href="#">Questions</a>
          <span class="crumbs-span">/</span>
          <span class="current">This is my first Question</span>
        </div>
      </div>
    </div>
    <!-- End row -->
  </section>
  <!-- End container -->
</div>
<!-- End breadcrumbs -->


<div class="col-md-12">
    <div class="boxedtitle" style="background: #ff7361; color: white; padding-left: 20px; margin-bottom: 30px;">
        <h2 style="text-align: center;padding-top: 15px;padding-bottom: 15px;color: #fff;">Do You want to Delete this Question?</h2>
    </div>
</div>


<section class="container main-content">
    <div class="row" style="
    width: 100;
    justify-content: center;
    display: flex;
">
    <div class="col-md-9" style="width:100%;">
     
        <form method="post" action="{% url 'base:question_delete' question.slug %}" class="question single-question question-type-normal" style="
        height: 90px;
        display: flex;
        justify-content: center;
    ">
            {% csrf_token %}
            <button type="submit" class="button medium red-button">Delete</button>
            <a href="{% url 'base:question_detail' question.slug %}" class="button medium gray-button btn-outline-warning">Cancel</a>
        </form>

             
   

      <!-- End about-author -->


      <!-- End post-next-prev -->
    </div>
    <!-- End main -->

    <!-- End sidebar -->
  </div>
  <!-- End row -->
</section>

{% endblock content %}

base/templates/base/question_form.html
{% extends "base.html" %} {% block content %} {% load humanize %}







<div class="breadcrumbs" style="padding-top:86px">
  <section class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Ask Question</h1>
      </div>
      <div class="col-md-12">
        <div class="crumbs">
          <a href="#">Home</a>
          <span class="crumbs-span">/</span>
          <a href="#">Pages</a>
          <span class="crumbs-span">/</span>
          <span class="current">Ask Question</span>
        </div>
      </div>
    </div>
    <!-- End row -->
  </section>
  <!-- End container -->
</div>
<!-- End breadcrumbs -->


	
<header id="header" class="fixed-header
" style="
position: fixed;
top: 50px;
width: 100%;
background-color: #2f3239; /* Set the background color as needed */
z-index: 1000; /* Ensure the header is above other elements */
 /* Add smooth transition effect */
">
<section class="container clearfix">
  <div class="logo"><a href="{% url "base:home"%}"><img alt="" src="/static/images/logo2.png"></a></div>
  <nav class="navigation">
    <ul>
      <li><a href="{% url "base:home"%}">Home</a>
        <ul>
          <li><a href="index.html">Home</a></li>
          <li><a href="index_2.html">Home 2</a></li>
          <li><a href="index_boxed_1.html">Home Boxed 1</a></li>
          <li><a href="index_boxed_2.html">Home Boxed 2</a></li>
          <li><a href="index_no_box.html">Home No Box</a></li>
        </ul>
      </li>
      {% if user.is_authenticated %}

        <li class="ask_question current_page_item"><a href="{% url 'base:question_create' %}">Ask Question</a></li>
      {% else %}
        <li class="ask_question"><a href="{% url 'login' %}">Ask Question</a></li>
      
      {% endif %}
      
      <li><a href="cat_question.html">Questions</a>
        <ul>
          <li><a href="cat_question.html">Questions Category</a></li>
          <li><a href="single_question.html">Question Single</a></li>
          
        </ul>
      </li>
      <li><a href="user_profile.html">User</a>
        <ul>
          <li><a href="user_profile.html">User Profile</a></li>
          <li><a href="user_questions.html">User Questions</a></li>
          <li><a href="user_answers.html">User Answers</a></li>
          <li><a href="user_favorite_questions.html">User Favorite Questions</a></li>
          <li><a href="user_points.html">User Points</a></li>
          <li><a href="edit_profile.html">Edit Profile</a></li>
        </ul>
      </li>
      <li><a href="blog_1.html">Blog</a>
        <ul>
          <li><a href="blog_1.html">Blog 1</a>
            <ul>
              <li><a href="blog_1.html">Right sidebar</a></li>
              <li><a href="blog_1_l_sidebar.html">Left sidebar</a></li>
              <li><a href="blog_1_full_width.html">Full Width</a></li>
            </ul>
          </li>
          <li><a href="blog_2.html">Blog 2</a>
            <ul>
              <li><a href="blog_2.html">Right sidebar</a></li>
              <li><a href="blog_2_l_sidebar.html">Left sidebar</a></li>
              <li><a href="blog_2_full_width.html">Full Width</a></li>
            </ul>
          </li>
          <li><a href="single_post.html">Post Single</a>
            <ul>
              <li><a href="single_post.html">Right sidebar</a></li>
              <li><a href="single_post_l_sidebar.html">Left sidebar</a></li>
              <li><a href="single_post_full_width.html">Full Width</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <li><a href="right_sidebar.html">Pages</a>
        <ul>
          <li><a href="login.html">Login</a></li>
          <li><a href="contact_us.html">Contact Us</a></li>
          <li><a href="ask_question.html">Ask Question</a></li>
          <li><a href="right_sidebar.html">Right Sidebar</a></li>
          <li><a href="left_sidebar.html">Left Sidebar</a></li>
          <li><a href="full_width.html">Full Width</a></li>
          <li><a href="404.html">404</a></li>
        </ul> 
      </li>
      <li><a href="shortcodes.html">Shortcodes</a></li>
      <li><a href="contact_us.html">Contact Us</a></li>
      {% comment %} <li><a href="contact_us.html"><img style="    width: 40px; height: 40px;" src="{% static 'images/patterns/bg13.png' %}"></img></a></li> {% endcomment %}
      
      {% if user.is_authenticated %}
      
        <li><a href="{% url "logout" %}">Logout</a></li>
      {% endif %}
    </ul>
  </nav>
</section><!-- End container -->
</header><!-- End header -->


<div>
{% if messages %}
  {% for message in messages %}
    
  <div class="alert-message success {{ message.tags }}">
    <i class="icon-ok"></i>
    <p>
      <span>Success Message</span><br>
      {{ message }}
    </p>
    </div>

  <!-- <div class= "alert alert - {{ message.tags }}", role="alert"> 
      <h4 style="text-align:center">{{ message }} <h4>

    </div> -->
  {% endfor %}
{% endif %}
</div>




  <!-- End container -->

<section class="container main-content">
  <div class="row">
    <div class="col-md-9">
      <div class="page-content ask-question">
        <div class="boxedtitle page-title"><h2>Ask Question</h2></div>

        <p>ok</p>

        <div class="form-style form-style-3" id="question-submit">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} {{form}}
   
            {{ form.media }}

            <p class="form-submit">
              <a href="{% url "base:question_list" %}" class="button medium gray-button" style="
    width: 100%;
    /* align-items: center; */
    align-self: center;
    display: flex;
    justify-content: center;
    /* align-items: center; */
    /* text-align: center; */
">Cancel</a>
              <input
                type="submit"
                id="publish-question"
                value="Publish Your Question"
                class="button color small submit"
              />
            </p>
          </form>
        </div>
      </div>
      <!-- End page-content -->
    </div>
    <!-- End main -->
    <aside class="col-md-3 sidebar">
      <div class="widget widget_stats">
        <h3 class="widget_title">Stats</h3>
        <div class="ul_list ul_list-icon-ok">
          <ul>
            <li>
              <i class="icon-question-sign"></i>Questions ( <span>20</span> )
            </li>
            <li><i class="icon-comment"></i>Answers ( <span>50</span> )</li>
          </ul>
        </div>
      </div>

      <div class="widget widget_social">
        <h3 class="widget_title">Find Us</h3>
        <ul>
          <li class="rss-subscribers">
            <a href="#" target="_blank">
              <strong>
                <i class="icon-rss"></i>
                <span>Subscribe</span><br />
                <small>To RSS Feed</small>
              </strong>
            </a>
          </li>
          <li class="facebook-fans">
            <a href="#" target="_blank">
              <strong>
                <i class="social_icon-facebook"></i>
                <span>5,000</span><br />
                <small>People like it</small>
              </strong>
            </a>
          </li>
          <li class="twitter-followers">
            <a href="#" target="_blank">
              <strong>
                <i class="social_icon-twitter"></i>
                <span>3,000</span><br />
                <small>Followers</small>
              </strong>
            </a>
          </li>
          <li class="youtube-subs">
            <a href="#" target="_blank">
              <strong>
                <i class="icon-play"></i>
                <span>1,000</span><br />
                <small>Subscribers</small>
              </strong>
            </a>
          </li>
        </ul>
      </div>

      <div class="widget widget_login">
        <h3 class="widget_title">Login</h3>
        <div class="form-style form-style-2">
          <form>
            <div class="form-inputs clearfix">
              <p class="login-text">
                <input
                  type="text"
                  value="Username"
                  onfocus="if (this.value == 'Username') {this.value = '';}"
                  onblur="if (this.value == '') {this.value = 'Username';}"
                />
                <i class="icon-user"></i>
              </p>
              <p class="login-password">
                <input
                  type="password"
                  value="Password"
                  onfocus="if (this.value == 'Password') {this.value = '';}"
                  onblur="if (this.value == '') {this.value = 'Password';}"
                />
                <i class="icon-lock"></i>
                <a href="#">Forget</a>
              </p>
            </div>
            <p class="form-submit login-submit">
              <input
                type="submit"
                value="Log in"
                class="button color small login-submit submit"
              />
            </p>
            <div class="rememberme">
              <label
                ><input type="checkbox" checked="checked" /> Remember Me</label
              >
            </div>
          </form>
          <ul class="login-links login-links-r">
            <li><a href="#">Register</a></li>
          </ul>
          <div class="clearfix"></div>
        </div>
      </div>

      <div class="widget widget_highest_points">
        <h3 class="widget_title">Highest points</h3>
        <ul>
          <li>
            <div class="author-img">
              <a href="#"
                ><img
                  width="60"
                  height="60"
                  src="../ask-me/images/demo/admin.jpg"
                  alt=""
              /></a>
            </div>
            <h6><a href="#">admin</a></h6>
            <span class="comment">12 Points</span>
          </li>
          <li>
            <div class="author-img">
              <a href="#"
                ><img
                  width="60"
                  height="60"
                  src="../ask-me/images/demo/avatar.png"
                  alt=""
              /></a>
            </div>
            <h6><a href="#">vbegy</a></h6>
            <span class="comment">10 Points</span>
          </li>
          <li>
            <div class="author-img">
              <a href="#"
                ><img
                  width="60"
                  height="60"
                  src="../ask-me/images/demo/avatar.png"
                  alt=""
              /></a>
            </div>
            <h6><a href="#">ahmed</a></h6>
            <span class="comment">5 Points</span>
          </li>
        </ul>
      </div>

      <div class="widget widget_tag_cloud">
        <h3 class="widget_title">Tags</h3>
        <a href="#">projects</a>
        <a href="#">Portfolio</a>
        <a href="#">Wordpress</a>
        <a href="#">Html</a>
        <a href="#">Css</a>
        <a href="#">jQuery</a>
        <a href="#">2code</a>
        <a href="#">vbegy</a>
      </div>

      <div class="widget">
        <h3 class="widget_title">Recent Questions</h3>
        <ul class="related-posts">
          <li class="related-item">
            <h3><a href="#">This is my first Question</a></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <div class="clear"></div>
            <span>Feb 22, 2014</span>
          </li>
          <li class="related-item">
            <h3><a href="#">This Is My Second Poll Question</a></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <div class="clear"></div>
            <span>Feb 22, 2014</span>
          </li>
        </ul>
      </div>
    </aside>
    <!-- End sidebar -->
  </div>
  <!-- End row -->
</section>
<!-- End container -->

{% endblock content%}